"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, Loader2, Send } from "lucide-react";
import * as api from "./rfid-api";
import type { RfidCard } from "@/types";
const statusLabels = { pending: "Chờ xử lý", processing: "Đang xử lý", completed: "Hoàn tất", rejected: "Từ chối" } as const;
export function MemberRfidIssuePanel() {
  const [cards, setCards] = useState<RfidCard[]>([]); const [requests, setRequests] = useState<api.RfidIssueRequest[]>([]); const [cardId, setCardId] = useState(""); const [type, setType] = useState<"lost" | "damaged">("lost"); const [description, setDescription] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  async function load() { setLoading(true); try { const results = await Promise.all([api.fetchMyRfidCards(), api.fetchMyRfidIssues()]); if (results[0].ok) { const data = await results[0].json(); setCards((data.cards || []).filter((card: RfidCard) => ["active", "in-use"].includes(card.status))); } if (results[1].ok) { const data = await results[1].json(); setRequests(data.requests || []); } } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!cardId) return; setSending(true); setMessage(""); try { const response = await api.createMyRfidIssue({ rfidCardId: cardId, type, description: description.trim() || undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Không gửi được yêu cầu."); setMessage("Đã gửi yêu cầu báo lỗi RFID."); setCardId(""); setDescription(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Không gửi được yêu cầu."); } finally { setSending(false); } }
  return <section className="panel" style={{ marginTop: 20 }}><div className="panel-header"><div><h3><AlertTriangle size={18} /> Báo mất hoặc hỏng thẻ RFID</h3><p className="muted-text">Gửi yêu cầu để Parking Manager kiểm tra và xử lý thẻ đang gắn với phương tiện của bạn.</p></div></div>{message && <p className="action-log">{message}</p>}{loading ? <p>Đang tải thẻ RFID...</p> : <form onSubmit={submit} style={{ display: "grid", gap: 12 }}><label>Thẻ RFID / phương tiện<select value={cardId} onChange={(event) => setCardId(event.target.value)} required><option value="">Chọn thẻ cần báo lỗi</option>{cards.map((card) => <option key={card.id} value={card.id}>{card.cardId || card.uid} — {card.plate || "Chưa gắn xe"}</option>)}</select></label><label>Loại sự cố<select value={type} onChange={(event) => setType(event.target.value as "lost" | "damaged")}><option value="lost">Lost — Báo mất</option><option value="damaged">Damaged — Báo hỏng</option></select></label><label>Mô tả bổ sung<textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={1000} placeholder="Mô tả tình trạng thẻ hoặc thời điểm bị mất..." rows={3} /></label><button className="small-button primary" disabled={sending}>{sending ? <Loader2 size={14} /> : <Send size={14} />} Gửi yêu cầu</button></form>}<div style={{ marginTop: 20 }}><h4>Lịch sử yêu cầu</h4>{requests.length === 0 ? <p className="muted-text">Chưa có yêu cầu nào.</p> : requests.map((item) => <div key={item.id} style={{ padding: "10px 0", borderBottom: "1px solid var(--border)" }}><strong>{item.type === "lost" ? "Báo mất" : "Báo hỏng"} — {item.card?.plate || item.uid}</strong><span className="badge warning" style={{ marginLeft: 8 }}>{statusLabels[item.status]}</span><div className="muted-text">{new Date(item.createdAt).toLocaleString("vi-VN")}{item.managerNote ? " — " + item.managerNote : ""}</div></div>)}</div></section>;
}
