"use client";
import { useEffect, useState } from "react";
import * as api from "./rfid-api";
const labels: Record<string,string> = { pending_payment:"Chờ thanh toán", waiting_issuance:"Đã thanh toán · chờ duyệt cấp thẻ", approved_waiting_assignment:"Đã duyệt · chờ quét UID", completed:"Đã bàn giao", rejected:"Từ chối" };
export function RfidIssueManagerPanel() {
 const [items,setItems]=useState<api.RfidPurchaseRequest[]>([]); const [uid,setUid]=useState<Record<string,string>>({}); const [note,setNote]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await api.fetchRfidPurchaseRequests();const d=await r.json();if(r.ok)setItems(d.requests||[]);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function action(id:string,action:"approve"|"reject"){const r=await api.reviewRfidPurchaseRequest(id,{action,reason:note[id]});const d=await r.json();setMessage(r.ok?"Đã cập nhật yêu cầu.":d.message||"Không thể cập nhật.");if(r.ok)await load();}
 async function assign(id:string){const r=await api.assignRfidPurchaseCard(id,{uid:uid[id]||""});const d=await r.json();setMessage(r.ok?"Đã gán thẻ kho và hoàn tất bàn giao.":d.message||"Không thể cấp thẻ.");if(r.ok)await load();}
 return <section className="panel" style={{marginBottom:20}}><div className="panel-header"><div><h3>Yêu cầu mua và cấp RFID Member</h3><p className="muted-text">Chỉ xử lý yêu cầu đã thanh toán: duyệt, quét UID thẻ trống trong kho và bàn giao cho thành viên.</p></div></div>{message&&<p className="action-log">{message}</p>}{loading?<p>Đang tải yêu cầu...</p>:items.length===0?<p className="muted-text">Chưa có yêu cầu mua thẻ nào.</p>:<div style={{display:"grid",gap:12}}>{items.map(item=><div key={item.id} style={{border:"1px solid var(--border)",borderRadius:10,padding:14}}><strong>{item.vehicle?.plate||"—"}</strong> · {item.vehicle?.ownerName||"Thành viên"}<span className="badge warning" style={{marginLeft:8}}>{labels[item.status]}</span><p className="muted-text" style={{margin:"7px 0"}}>Phí phát hành: {new Intl.NumberFormat("vi-VN").format(item.salePrice)} ₫ · {new Date(item.createdAt).toLocaleString("vi-VN")}</p>{item.status==="waiting_issuance"&&<><textarea rows={2} placeholder="Lý do từ chối hoặc ghi chú duyệt" value={note[item.id]||""} onChange={e=>setNote({...note,[item.id]:e.target.value})} style={{width:"100%",marginBottom:8}}/><div style={{display:"flex",gap:8}}><button className="small-button primary" onClick={()=>void action(item.id,"approve")}>Duyệt yêu cầu</button><button className="small-button" onClick={()=>void action(item.id,"reject")}>Từ chối</button></div></>}{item.status==="approved_waiting_assignment"&&<div style={{display:"flex",gap:8}}><input value={uid[item.id]||""} onChange={e=>setUid({...uid,[item.id]:e.target.value})} placeholder="Quét UID thẻ trống trong kho"/><button className="small-button primary" onClick={()=>void assign(item.id)}>Cấp và gán thẻ</button></div>}{item.status==="pending_payment"&&<p className="muted-text">Đang chờ thành viên thanh toán QR.</p>}{item.status==="completed"&&<p className="muted-text success">Đã hoàn tất cấp thẻ: {item.card?.uid||"—"}</p>}</div>)}</div>}</section>;
}
