# -*- coding: utf-8 -*-
"""Định nghĩa 27 Use Case iPARK (UC01–UC27)."""

AUTO = (
    "Chế độ vận hành: TỰ ĐỘNG — hệ thống (AI, camera, sensor, thanh toán, barrier) "
    "thực hiện toàn bộ; không có thao tác thủ công từ nhân viên."
)
MANUAL_VEHICLE = (
    "Chế độ vận hành: Kê khai xe trước (mô hình vé tháng xe buýt) — khách kê khai biển số "
    "và thông tin xe một lần tại UC06; mua vé tháng (UC07) chỉ chọn biển đã kê khai; "
    "vào/ra bãi AI tự nhận diện, không nhập tay tại cổng."
)
STAFF_AUTO = (
    "Chế độ vận hành: TỰ ĐỘNG giám sát; nhân viên chỉ can thiệp khi hệ thống phát sinh "
    "sự cố (UC14) hoặc xử lý yêu cầu hỗ trợ khách hàng (UC16)."
)
ADMIN_CONFIG = "Chế độ vận hành: Admin cấu hình một lần; vận hành hàng ngày TỰ ĐỘNG."

USE_CASES = [
    # ─── GUEST ───
    {
        "id": "UC01",
        "actor_group": "Guest",
        "name": "Tra cứu tình trạng bãi đỗ",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách vãng lai (Guest)",
        "secondary_actors": "Hệ thống giám sát sức chứa",
        "summary": "Khách tra cứu realtime số chỗ trống, tỷ lệ lấp đầy và trạng thái bãi mà không cần đăng nhập.",
        "preconditions": "Hệ thống và cảm biến sức chứa đang hoạt động.",
        "postconditions": "Khách nhận được thông tin tình trạng bãi chính xác.",
        "trigger": "Khách truy cập trang chủ hoặc màn tra cứu công khai.",
        "basic_flow": [
            "Khách mở giao diện tra cứu công khai.",
            "Hệ thống tự động tổng hợp dữ liệu từ cảm biến và phiên đang gửi.",
            "Hệ thống tự tính số chỗ trống / đã dùng theo từng khu vực.",
            "Hệ thống hiển thị bảng giá khách vãng lai (tham chiếu UC18).",
            "Khách xem kết quả tra cứu.",
        ],
        "alternative_flows": ["2a. Lọc theo khu vực: Hệ thống tự lọc và cập nhật view."],
        "exception_flows": ["2a. Mất kết nối thiết bị: Hệ thống hiển thị dữ liệu gần nhất kèm cảnh báo (UC26)."],
        "special_requirements": AUTO,
        "related_uc": "UC13, UC18, UC20, UC21",
        "implementation": "Public overview API; landing page.",
    },
    {
        "id": "UC02",
        "actor_group": "Guest",
        "name": "Gửi xe vào bãi",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách vãng lai",
        "secondary_actors": "Camera AI lối vào, Barrier, Hệ thống cấp chỗ",
        "summary": "Xe vào bãi hoàn toàn tự động: AI nhận diện biển số, cấp vị trí, tạo phiên, mở barrier.",
        "preconditions": "Bãi còn chỗ trống; thiết bị lối vào online.",
        "postconditions": "ParkingSession trạng thái Đang gửi; barrier đã mở và đóng sau khi xe qua.",
        "trigger": "Xe đến cổng vào.",
        "basic_flow": [
            "Camera AI tự động chụp và nhận diện biển số.",
            "Hệ thống tự kiểm tra sức chứa và chọn vị trí đỗ tối ưu (UC21).",
            "Hệ thống tự tạo phiên đỗ khách vãng lai.",
            "Hệ thống tự gửi thông báo/hướng dẫn (nếu khách có tài khoản — UC11).",
            "Barrier tự động mở cho xe vào.",
            "Hệ thống tự ghi nhật ký sự kiện vào (UC26).",
        ],
        "alternative_flows": [
            "1a. Xe đã kê khai và có gói vé tháng: Hệ thống tự liên kết membership (UC06, UC07, UC08).",
            "2a. Bãi gần đầy: Hệ thống tự đề xuất khu vực còn chỗ (UC20).",
        ],
        "exception_flows": [
            "1a. AI không đọc được biển: Hệ thống tự tạo sự cố và chuyển UC14 (staff xử lý).",
            "2a. Bãi đầy: Barrier không mở; hiển thị thông báo tự động.",
        ],
        "special_requirements": AUTO,
        "related_uc": "UC06, UC07, UC08, UC13, UC14, UC21",
        "implementation": "camera-entry API; AI OCR; auto slot allocation.",
    },
    {
        "id": "UC03",
        "actor_group": "Guest",
        "name": "Lấy xe ra khỏi bãi",
        "automation": AUTO,
        "includes": ["UC04"],
        "primary_actor": "Khách vãng lai",
        "secondary_actors": "Camera AI lối ra, Barrier, Hệ thống tính phí",
        "summary": "Xe ra bãi tự động: AI nhận diện, khớp phiên, tính phí, thanh toán, mở barrier.",
        "preconditions": "Xe có phiên Đang gửi trong hệ thống.",
        "postconditions": "Phiên hoàn thành; phí đã thanh toán (hoặc trừ ví thành viên).",
        "trigger": "Xe đến cổng ra.",
        "basic_flow": [
            "Camera AI tự nhận diện biển số lối ra.",
            "Hệ thống tự tìm và khớp phiên đang gửi.",
            "Hệ thống tự so khớp ảnh vào/ra (chống tráo biển).",
            "Hệ thống tự gọi «include» UC04 Thanh toán phí đỗ xe.",
            "Barrier tự động mở sau khi thanh toán thành công.",
            "Hệ thống tự cập nhật sức chứa và gửi biên lai điện tử.",
        ],
        "alternative_flows": ["4a. Thành viên còn hạn gói: Hệ thống tự miễn/giảm phí theo gói (UC08)."],
        "exception_flows": [
            "3a. Không khớp phiên/ảnh: Hệ thống tự tạo sự cố UC14; chặn barrier đến khi xử lý.",
        ],
        "special_requirements": AUTO + " «include» UC04.",
        "related_uc": "UC04, UC08, UC14",
        "implementation": "camera-exit; finalizeCheckout; VietQR.",
    },
    {
        "id": "UC04",
        "actor_group": "Guest",
        "name": "Thanh toán phí đỗ xe",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Hệ thống thanh toán",
        "secondary_actors": "Khách vãng lai, Cổng VietQR/Ngân hàng",
        "summary": "Tự động tính phí theo thời gian đỗ và thu qua VietQR/ví; đồng bộ kết quả không cần nhân viên.",
        "preconditions": "Phiên sắp kết thúc hoặc đã có checkOutAt.",
        "postconditions": "Transaction trạng thái Đã thanh toán.",
        "trigger": "UC03 kích hoạt checkout.",
        "basic_flow": [
            "Hệ thống tự tính phí theo biểu phí khách (UC18).",
            "Hệ thống tự tạo giao dịch và mã VietQR động.",
            "Khách quét QR bằng app ngân hàng (thao tác duy nhất phía khách).",
            "Hệ thống tự đồng bộ/ xác nhận thanh toán từ ngân hàng.",
            "Hệ thống tự cập nhật phiên và mở barrier (UC03).",
        ],
        "alternative_flows": [
            "3a. Thanh toán ví thành viên: Hệ thống tự trừ ví nếu đủ số dư.",
        ],
        "exception_flows": ["4a. Thanh toán thất bại/hết hạn QR: Hệ thống tự tạo QR mới."],
        "special_requirements": AUTO,
        "related_uc": "UC03, UC10, UC18, UC22",
        "implementation": "transaction.service; VietQR.",
    },
    # ─── CUSTOMER ───
    {
        "id": "UC05",
        "actor_group": "Customer",
        "name": "Quản lý hồ sơ cá nhân",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách hàng (Customer)",
        "secondary_actors": "Hệ thống xác thực",
        "summary": "Khách xem và cập nhật hồ sơ; đồng bộ tự động sau đăng nhập.",
        "preconditions": "Khách đã đăng nhập.",
        "postconditions": "Hồ sơ được hiển thị/cập nhật trên MongoDB.",
        "trigger": "Khách truy cập /dashboard/profile.",
        "basic_flow": [
            "Hệ thống tự tải thông tin từ session JWT.",
            "Khách xem/sửa thông tin cá nhân được phép.",
            "Hệ thống tự validate và lưu.",
            "Hệ thống tự đồng bộ hiển thị ví, gói, thông báo.",
        ],
        "alternative_flows": [],
        "exception_flows": ["3a. Dữ liệu không hợp lệ: Hệ thống tự báo lỗi validation."],
        "special_requirements": AUTO,
        "related_uc": "UC06, UC08, UC10",
        "implementation": "profile-view; auth/me.",
    },
    {
        "id": "UC06",
        "actor_group": "Customer",
        "name": "Quản lý phương tiện",
        "automation": MANUAL_VEHICLE,
        "includes": ["Kê khai xe", "Sửa thông tin xe", "Xóa xe đã kê khai"],
        "primary_actor": "Khách hàng (Customer)",
        "secondary_actors": "Hệ thống đăng ký xe",
        "summary": (
            "Khách kê khai xe (biển số, chủ xe, nhãn hiệu, model, màu...) một lần trước khi dùng dịch vụ; "
            "xe đã kê khai được AI tự nhận diện khi vào/ra — không nhập tay tại bãi."
        ),
        "preconditions": "Khách đã đăng nhập.",
        "postconditions": "Vehicle đã kê khai được lưu, gắn ownerUserId; sẵn sàng gắn vé tháng (UC07).",
        "trigger": "Khách mở Quản lý phương tiện / Kê khai xe.",
        "basic_flow": [
            "Khách mở mục Quản lý phương tiện.",
            "Khách kê khai biển số và thông tin xe (họ tên chủ, nhãn hiệu, model, màu, năm SX...).",
            "Hệ thống tự validate định dạng biển số và kiểm tra trùng.",
            "Hệ thống tự lưu Vehicle và gắn ownerUserId.",
            "Xe đã kê khai: khi vào/ra bãi AI tự nhận diện biển và áp dụng ưu đãi gói nếu đã mua vé tháng (UC02, UC03, UC07).",
        ],
        "alternative_flows": [
            "2a. Sửa/xóa xe đã kê khai: Khách cập nhật form; hệ thống tự đồng bộ DB và gói thành viên (UC08)."
        ],
        "exception_flows": ["3a. Biển trùng hoặc dữ liệu không hợp lệ: Hệ thống tự từ chối và báo lỗi."],
        "special_requirements": MANUAL_VEHICLE + " «include» Kê khai xe.",
        "related_uc": "UC07, UC08, UC02, UC03",
        "implementation": "vehicles API; form kê khai xe (dashboard vehicles/membership).",
    },
    # ─── MEMBER ───
    {
        "id": "UC07",
        "actor_group": "Member",
        "name": "Đăng ký thành viên",
        "automation": AUTO,
        "includes": [
            "Xem danh sách gói",
            "Mua gói",
            "Chọn biển số xe đã kê khai",
            "Thanh toán",
        ],
        "primary_actor": "Khách hàng",
        "secondary_actors": "Hệ thống thanh toán, Catalog gói (UC19)",
        "summary": (
            "Mua gói vé tháng: chọn gói, chọn biển số từ xe đã kê khai (UC06), thanh toán tự động; "
            "không nhập thông tin xe tại bước mua gói — giống mô hình đăng ký vé tháng xe buýt."
        ),
        "preconditions": "Khách đã đăng nhập; đã kê khai ít nhất một xe (UC06); có gói active trong catalog (UC19).",
        "postconditions": "Gói vé tháng được kích hoạt; biển số đã chọn được gắn membership; xe vào/ra tự động.",
        "trigger": "Khách chọn Đăng ký / Mua gói thành viên.",
        "basic_flow": [
            "«Include» Hệ thống tự hiển thị danh sách gói (UC19).",
            "Khách chọn gói vé tháng — «Include» Mua gói.",
            "Khách chọn biển số xe đã kê khai (UC06) để gắn vào gói — không nhập thêm thông tin xe.",
            "«Include» Hệ thống tự tạo VietQR/thu ví — Thanh toán.",
            "Hệ thống tự kích hoạt membership, liên kết biển số đã chọn và gửi thông báo (UC11).",
        ],
        "alternative_flows": [
            "4a. Thanh toán ví: Hệ thống tự trừ nếu đủ số dư.",
            "3a. Chọn thêm biển (theo hạn mức gói): Hệ thống tự liên kết nhiều xe đã kê khai.",
        ],
        "exception_flows": [
            "3a. Chưa kê khai xe: Hệ thống yêu cầu sang UC06 kê khai trước.",
            "4a. Thanh toán thất bại: Hệ thống tự hủy đơn đăng ký tạm.",
        ],
        "special_requirements": AUTO + " «include» Xem gói, Mua gói, Chọn biển đã kê khai, Thanh toán.",
        "related_uc": "UC06, UC08, UC19",
        "implementation": "wallet-view / membership; chọn biển từ danh sách xe đã kê khai.",
    },
    {
        "id": "UC08",
        "actor_group": "Member",
        "name": "Quản lý thành viên của tôi",
        "automation": AUTO,
        "includes": ["Gia hạn gói", "Hủy gói", "Xem trạng thái gói", "Xem thời hạn"],
        "primary_actor": "Thành viên",
        "secondary_actors": "Hệ thống billing",
        "summary": "Thành viên xem và quản lý gói; gia hạn/hủy xử lý tự động qua thanh toán.",
        "preconditions": "Đã có gói thành viên (UC07).",
        "postconditions": "Trạng thái gói cập nhật trên hệ thống.",
        "trigger": "Thành viên mở mục Gói của tôi.",
        "basic_flow": [
            "«Include» Hệ thống tự hiển thị trạng thái gói và thời hạn.",
            "Thành viên chọn Gia hạn hoặc Hủy.",
            "Gia hạn: Hệ thống tự tính phí và thanh toán (UC04).",
            "Hủy: Hệ thống tự cập nhật trạng thái cuối kỳ.",
            "Hệ thống tự gửi thông báo xác nhận (UC11).",
        ],
        "alternative_flows": [],
        "exception_flows": ["3a. Không đủ ví: Hệ thống tự chuyển VietQR."],
        "special_requirements": AUTO + " «include» Gia hạn, Hủy, Xem trạng thái, Xem thời hạn.",
        "related_uc": "UC07, UC11, UC19",
        "implementation": "profile/wallet membership section.",
    },
    {
        "id": "UC09",
        "actor_group": "Customer",
        "name": "Xem lịch sử đỗ xe",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách hàng",
        "secondary_actors": "—",
        "summary": "Khách xem danh sách phiên đã hoàn thành; dữ liệu tự đồng bộ từ DB.",
        "preconditions": "Đã đăng nhập.",
        "postconditions": "Lịch sử hiển thị đúng theo user.",
        "trigger": "Khách mở Lịch sử đỗ xe.",
        "basic_flow": [
            "Khách mở màn Lịch sử đỗ xe trên dashboard.",
            "Hệ thống tự gọi API parking-sessions lọc theo ownerUserId.",
            "Hệ thống tự sắp xếp theo thời gian và phân trang kết quả.",
            "Khách xem chi tiết từng phiên (vào/ra, phí, chỗ).",
        ],
        "alternative_flows": ["3a. Lọc theo biển số/ngày: Hệ thống tự lọc server-side."],
        "exception_flows": [],
        "special_requirements": AUTO,
        "related_uc": "UC10, UC05",
        "implementation": "sessions API + profile.",
    },
    {
        "id": "UC10",
        "actor_group": "Customer",
        "name": "Xem lịch sử giao dịch",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách hàng",
        "secondary_actors": "—",
        "summary": "Xem giao dịch thanh toán, VietQR, ví — tự đồng bộ.",
        "preconditions": "Đã đăng nhập.",
        "postconditions": "Danh sách transaction hiển thị.",
        "trigger": "Khách mở Ví / Lịch sử giao dịch.",
        "basic_flow": [
            "Khách mở màn Ví / Lịch sử giao dịch.",
            "Hệ thống tự tải GET /transactions theo user.",
            "Hệ thống tự hiển thị trạng thái, số tiền, phương thức.",
            "Khách tải biên lai/QR (nếu có) tự động sinh.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": AUTO,
        "related_uc": "UC04, UC22",
        "implementation": "wallet-view; transactions API.",
    },
    {
        "id": "UC11",
        "actor_group": "Customer",
        "name": "Xem thông báo",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách hàng",
        "secondary_actors": "Hệ thống notification",
        "summary": "Nhận và xem thông báo tự động: vào/ra bãi, thanh toán, gói thành viên.",
        "preconditions": "Đã đăng nhập.",
        "postconditions": "Thông báo được đánh dấu đã đọc.",
        "trigger": "Sự kiện nghiệp vụ hoặc khách mở màn Thông báo.",
        "basic_flow": [
            "Hệ thống tự sinh notification khi có sự kiện (UC02–UC04, UC07–UC08).",
            "Khách mở /dashboard/notifications.",
            "Hệ thống tự tải danh sách.",
            "Khách đánh dấu đã đọc — hệ thống tự lưu.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": AUTO,
        "related_uc": "UC02, UC04, UC07, UC23",
        "implementation": "notifications-view.",
    },
    {
        "id": "UC12",
        "actor_group": "Customer",
        "name": "Đánh giá dịch vụ",
        "automation": AUTO,
        "includes": [],
        "primary_actor": "Khách hàng",
        "secondary_actors": "—",
        "summary": "Sau phiên hoàn thành, hệ thống tự mời đánh giá; khách gửi feedback.",
        "preconditions": "Có ít nhất một phiên đã hoàn thành.",
        "postconditions": "Feedback được lưu.",
        "trigger": "Hệ thống tự gửi lời mời sau UC03 hoặc khách mở form.",
        "basic_flow": [
            "Hệ thống tự gửi thông báo mời đánh giá (UC11).",
            "Khách nhập sao và nội dung.",
            "Hệ thống tự lưu POST /feedback.",
            "Hệ thống tự cập nhật dashboard phản hồi cho staff (UC16).",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": AUTO,
        "related_uc": "UC11, UC16",
        "implementation": "feedback-view.",
    },
    # ─── STAFF ───
    {
        "id": "UC13",
        "actor_group": "Staff",
        "name": "Giám sát hoạt động bãi đỗ",
        "automation": STAFF_AUTO,
        "includes": [],
        "primary_actor": "Nhân viên (Staff)",
        "secondary_actors": "Dashboard realtime, AI, Camera",
        "summary": "Staff theo dõi realtime phiên, sức chứa, thiết bị — dữ liệu tự cập nhật, không nhập liệu thủ công.",
        "preconditions": "Staff đã đăng nhập.",
        "postconditions": "Staff nắm tình hình vận hành.",
        "trigger": "Staff mở dashboard vận hành.",
        "basic_flow": [
            "Staff mở dashboard vận hành /dashboard/overview.",
            "Hệ thống tự aggregate phiên đang gửi, doanh thu, occupancy.",
            "Hệ thống tự refresh dashboard định kỳ.",
            "Staff quan sát; can thiệp chỉ khi có cảnh báo (UC14).",
        ],
        "alternative_flows": ["2a. Lọc/tìm biển số: Hệ thống tự search."],
        "exception_flows": [],
        "special_requirements": STAFF_AUTO,
        "related_uc": "UC01, UC02, UC03, UC26",
        "implementation": "overview, sessions dashboard.",
    },
    {
        "id": "UC14",
        "actor_group": "Staff",
        "name": "Xử lý sự cố vận hành",
        "automation": STAFF_AUTO,
        "includes": [
            "Máy quét biển số AI lỗi",
            "Mất kết nối thiết bị (camera, sensor)",
            "Khiếu nại khẩn cấp từ khách",
        ],
        "primary_actor": "Nhân viên",
        "secondary_actors": "Hệ thống giám sát, UC24",
        "summary": "Hệ thống TỰ phát hiện sự cố; staff xử lý khi tự động không thể hoàn tất (AI lỗi, mất kết nối, khiếu nại).",
        "preconditions": "Hệ thống tạo incident tự động hoặc staff nhận cảnh báo.",
        "postconditions": "Sự cố được resolve; vận hành tự động trở lại.",
        "trigger": "Cảnh báo từ UC26 hoặc barrier/AI fail.",
        "basic_flow": [
            "Hệ thống tự tạo incident và phân loại mức độ.",
            "«Include» Staff xử lý theo loại: AI lỗi / mất kết nối / khiếu nại khẩn.",
            "Staff thực hiện hành động khắc phục (khởi động lại thiết bị, hỗ trợ khách).",
            "Hệ thống tự xác nhận thiết bị online trở lại.",
            "Staff đóng incident — hệ thống tự ghi log.",
        ],
        "alternative_flows": [],
        "exception_flows": ["3a. Không khắc phục được: Escalate admin (UC24)."],
        "special_requirements": STAFF_AUTO + " «include» AI lỗi, mất kết nối, khiếu nại khẩn.",
        "related_uc": "UC24, UC26",
        "implementation": "incidents-view.",
    },
    {
        "id": "UC15",
        "actor_group": "Staff",
        "name": "Quản lý ca làm việc",
        "automation": STAFF_AUTO,
        "includes": [],
        "primary_actor": "Nhân viên",
        "secondary_actors": "Hệ thống chấm công",
        "summary": "Staff bắt đầu/kết thúc ca; hệ thống tự ghi nhận và báo cáo ca.",
        "preconditions": "Staff đã đăng nhập.",
        "postconditions": "Shift được lưu với thời gian vào/ra ca.",
        "trigger": "Staff bấm Bắt đầu/Kết thúc ca.",
        "basic_flow": [
            "Staff bấm Bắt đầu ca.",
            "Hệ thống tự ghi shift open.",
            "Trong ca: UC13 tự giám sát.",
            "Staff bấm Kết thúc ca — hệ thống tự tổng hợp sự cố đã xử lý.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": STAFF_AUTO,
        "related_uc": "UC13, UC14",
        "implementation": "shifts-view.",
    },
    {
        "id": "UC16",
        "actor_group": "Staff",
        "name": "Xử lý yêu cầu hỗ trợ khách hàng",
        "automation": STAFF_AUTO,
        "includes": ["Tiếp nhận ticket", "Phản hồi khách", "Đóng ticket"],
        "primary_actor": "Nhân viên",
        "secondary_actors": "Khách hàng",
        "summary": (
            "Staff tiếp nhận và xử lý yêu cầu hỗ trợ/khiếu nại từ khách (UC12) trong một luồng; "
            "hệ thống tự tạo ticket, gán nhân viên, gửi thông báo kết quả."
        ),
        "preconditions": "Khách đã gửi yêu cầu hoặc feedback (UC12).",
        "postconditions": "Ticket Đã xử lý; khách nhận thông báo (UC11).",
        "trigger": "Khách gửi form hỗ trợ/khiếu nại hoặc staff mở hàng đợi ticket.",
        "basic_flow": [
            "Hệ thống tự tạo ticket từ feedback/yêu cầu khách (UC12).",
            "Staff mở danh sách ticket và tiếp nhận — hệ thống tự gán staffId.",
            "Staff xem chi tiết yêu cầu.",
            "Staff nhập phản hồi và cách xử lý.",
            "Hệ thống tự gửi thông báo cho khách (UC11) và đóng ticket.",
        ],
        "alternative_flows": [
            "2a. Ticket đã có người nhận: Hệ thống chỉ cho phép staff được gán xử lý."
        ],
        "exception_flows": [
            "4a. Cần leo thang: Staff chuyển admin/UC14 nếu vượt quyền xử lý."
        ],
        "special_requirements": STAFF_AUTO + " «include» Tiếp nhận ticket, Phản hồi khách, Đóng ticket.",
        "related_uc": "UC12, UC11, UC14",
        "implementation": "feedback + support queue; tiếp nhận và xử lý trên cùng màn ticket.",
    },
    # ─── ADMIN ───
    {
        "id": "UC17",
        "actor_group": "Admin",
        "name": "Quản lý người dùng và phân quyền",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin quản lý user, role; vận hành đăng nhập/ phân quyền tự động sau cấu hình.",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "User/role cập nhật trên DB.",
        "trigger": "Admin mở /dashboard/users.",
        "basic_flow": [
            "Admin mở /dashboard/users.",
            "Hệ thống tự tải danh sách users.",
            "Admin tạo/sửa/khóa tài khoản và gán role.",
            "Hệ thống tự áp dụng RoleGuard trên frontend.",
        ],
        "alternative_flows": [],
        "exception_flows": ["2a. Không được hạ quyền admin cuối: Hệ thống tự chặn."],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC05",
        "implementation": "users API.",
    },
    {
        "id": "UC18",
        "actor_group": "Admin",
        "name": "Quản lý biểu phí khách vãng lai",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin cấu hình giá giờ/ngày/qua đêm; UC04 tự áp dụng khi tính phí.",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "PricingConfig cập nhật.",
        "trigger": "Admin sửa biểu phí.",
        "basic_flow": [
            "Admin mở cấu hình phí khách.",
            "Admin nhập hourlyRate, dailyMax, overnightRate, ...",
            "Hệ thống tự validate và lưu.",
            "UC04 tự dùng config mới cho phiên tiếp theo.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC04, UC01",
        "implementation": "pricing-config API.",
    },
    {
        "id": "UC19",
        "actor_group": "Admin",
        "name": "Quản lý gói thành viên",
        "automation": ADMIN_CONFIG,
        "includes": ["Tạo gói", "Cập nhật gói", "Ngưng áp dụng gói", "Xem danh sách đăng ký"],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin CRUD catalog gói; khách mua qua UC07 (chọn biển đã kê khai tại UC06) tự động sau thanh toán.",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "MembershipPackage cập nhật.",
        "trigger": "Admin mở quản lý gói thành viên.",
        "basic_flow": [
            "Admin mở màn quản lý gói thành viên.",
            "«Include» Xem danh sách gói và đăng ký.",
            "«Include» Tạo/Cập nhật/Ngưng gói.",
            "Hệ thống tự publish gói active lên UC07.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG + " «include» Tạo, Cập nhật, Ngưng, Xem đăng ký.",
        "related_uc": "UC07, UC08",
        "implementation": "membership-packages API.",
    },
    {
        "id": "UC20",
        "actor_group": "Admin",
        "name": "Quản lý khu vực đỗ xe",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin định nghĩa zone; hệ thống tự phân bổ chỗ khi xe vào (UC02).",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "Zone CRUD trên DB.",
        "trigger": "Admin quản lý zones.",
        "basic_flow": [
            "Admin mở màn quản lý khu vực /dashboard/zones.",
            "Admin tạo/sửa/xóa khu vực (tên, capacity, loại xe).",
            "Hệ thống tự validate tổng capacity.",
            "UC01, UC02 tự dùng dữ liệu zone.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC01, UC02, UC21",
        "implementation": "zones API.",
    },
    {
        "id": "UC21",
        "actor_group": "Admin",
        "name": "Quản lý vị trí đỗ xe",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "Hệ thống cấp chỗ tự động",
        "summary": "Admin cấu hình slot; UC02 tự allocate khi xe vào.",
        "preconditions": "Đã có zone (UC20).",
        "postconditions": "Slot map cập nhật.",
        "trigger": "Admin quản lý vị trí/slot.",
        "basic_flow": [
            "Admin mở màn quản lý vị trí/slot trong zone.",
            "Admin định nghĩa slot trong từng zone.",
            "Hệ thống tự theo dõi trạng thái occupied/free realtime.",
            "UC02 tự chọn slot trống tối ưu.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC02, UC20",
        "implementation": "allocateCarSlot; zones.",
    },
    {
        "id": "UC22",
        "actor_group": "Admin",
        "name": "Quản lý giao dịch thanh toán",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin xem/đối soát giao dịch; thanh toán khách chủ yếu tự động (UC04).",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "Báo cáo giao dịch chính xác.",
        "trigger": "Admin mở quản lý giao dịch.",
        "basic_flow": [
            "Admin mở màn quản lý giao dịch thanh toán.",
            "Hệ thống tự tải transactions.",
            "Admin lọc theo trạng thái/ngày.",
            "Hệ thống tự đối soát với phiên đỗ.",
        ],
        "alternative_flows": ["3a. Giao dịch treo: Admin xác nhận thủ công đối soát (ngoại lệ hiếm)."],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC04, UC10, UC25",
        "implementation": "transactions API.",
    },
    {
        "id": "UC23",
        "actor_group": "Admin",
        "name": "Quản lý thông báo",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin cấu hình template/thông báo hệ thống; gửi tự động theo sự kiện.",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "Cấu hình notification cập nhật.",
        "trigger": "Admin mở quản lý thông báo.",
        "basic_flow": [
            "Admin mở màn quản lý thông báo.",
            "Admin xem log thông báo đã gửi.",
            "Admin cấu hình template (nếu có).",
            "Hệ thống tự gửi theo trigger UC11.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC11",
        "implementation": "notifications admin.",
    },
    {
        "id": "UC24",
        "actor_group": "Admin",
        "name": "Quản lý sự cố vận hành",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "Staff (UC14)",
        "summary": "Admin giám sát và đóng sự cố leo thang; phần lớn phát hiện tự động.",
        "preconditions": "Có incident từ UC14/UC26.",
        "postconditions": "Incident được quản lý tập trung.",
        "trigger": "Admin mở quản lý sự cố.",
        "basic_flow": [
            "Admin mở màn quản lý sự cố vận hành.",
            "Hệ thống tự liệt kê incidents mở/đóng.",
            "Admin xem chi tiết và escalations.",
            "Admin đóng hoặc giao lại staff.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC14, UC26",
        "implementation": "incidents admin.",
    },
    {
        "id": "UC25",
        "actor_group": "Admin",
        "name": "Xem báo cáo hoạt động và doanh thu",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Báo cáo tự aggregate từ phiên và giao dịch; export tự động.",
        "preconditions": "Có dữ liệu phiên/transaction.",
        "postconditions": "Báo cáo/export được tạo.",
        "trigger": "Admin chọn khoảng thời gian báo cáo.",
        "basic_flow": [
            "Admin chọn from–to.",
            "Hệ thống tự aggregate revenue, sessions, occupancy.",
            "Hệ thống tự vẽ biểu đồ.",
            "Admin export Excel/PDF — hệ thống tự sinh file.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC22, UC13",
        "implementation": "revenue-reports API.",
    },
    {
        "id": "UC26",
        "actor_group": "Admin",
        "name": "Giám sát hệ thống",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "Camera, Sensor, AI, Backend",
        "summary": "Giám sát health API, thiết bị, AI; cảnh báo tự động khi lỗi.",
        "preconditions": "Monitoring agents hoạt động.",
        "postconditions": "Admin nắm tình trạng hệ thống.",
        "trigger": "Định kỳ hoặc cảnh báo realtime.",
        "basic_flow": [
            "Hệ thống tự ping health /api/health, devices online.",
            "Hệ thống tự theo dõi OCR success rate.",
            "Khi lỗi: Hệ thống tự tạo incident (UC14, UC24).",
            "Admin xem dashboard giám sát.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC14, UC24",
        "implementation": "devices, ai monitoring.",
    },
    {
        "id": "UC27",
        "actor_group": "Admin",
        "name": "Quản lý cấu hình hệ thống",
        "automation": ADMIN_CONFIG,
        "includes": [],
        "primary_actor": "Quản trị viên",
        "secondary_actors": "—",
        "summary": "Admin cấu hình payment, SMTP, capacity, barrier; vận hành tự động theo config.",
        "preconditions": "Admin đã đăng nhập.",
        "postconditions": "System config cập nhật.",
        "trigger": "Admin mở Cấu hình hệ thống.",
        "basic_flow": [
            "Admin mở màn Cấu hình hệ thống.",
            "Admin cấu hình PaymentConfig (VietQR), email, giới hạn bãi.",
            "Hệ thống tự validate và lưu .env/DB.",
            "Các UC vận hành tự dùng config mới.",
        ],
        "alternative_flows": [],
        "exception_flows": [],
        "special_requirements": ADMIN_CONFIG,
        "related_uc": "UC04, UC18, UC26",
        "implementation": "payment-config, pricing, security.",
    },
]
